import exampleStack from './Example/routes';

const Routes = {
  exampleStack,
  // Explore
  EXPLORE_SCREEN: 'EXPLORE_SCREEN',
  DETAIL_PROPERTY: 'DETAIL_PROPERTY',
  DETAIL_ROOM: 'DETAIL_ROOM',
  PROPERTY_BY_CATEGORY: 'PROPERTY_BY_CATEGORY',
  PROPERTY_BY_CITY: 'PROPERTY_BY_CITY',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  MAP_PROPERTIES: 'MAP_PROPERTIES',
  VIEW_360_DEGREES_IMAGE: 'VIEW_360_DEGREES_IMAGE',
  PROPERTY_NEAR_ME: 'PROPERTY_NEAR_ME',
  // Saved
  SAVED_SCREEN: 'SAVED_SCREEN',
  // Notification
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  // Profile
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  CREATE_PROPERTY: 'CREATE_PROPERTY',
  REGISTER_OWNER: 'REGISTER_OWNER',
  LIST_YOU_HAVE_BOOKED: 'LIST_YOU_HAVE_BOOKED',
  LIST_ROOM_HAVE_BEEN_BOOKED: 'LIST_ROOM_HAVE_BEEN_BOOKED',
  MY_LIST_PROPERTY: 'MY_LIST_PROPERTY',
  SELECT_LOCATION: 'SELECT_LOCATION',
  MANAGE_DETAIL_PROPERTY: 'MANAGE_DETAIL_PROPERTY',
  CREATE_ROOM: 'CREATE_ROOM',
  MY_ACCOUNT: 'MY_ACCOUNT',
  // Auth
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  // Auth
  DETAIL_ROOMMATE_SCREEN: 'DETAIL_ROOMMATE_SCREEN',
  // Chat
  CHAT_SCREEN: 'CHAT_SCREEN',
  CHAT_ROOM: 'CHAT_ROOM',
};

export default Routes;
