export enum RoleApi {
  ADMIN = 'ADMIN  ',
  MODERATOR = 'MODERATOR',
  OWNER = 'OWNER',
  USER = 'USER'
}

export const EVENT_APP_EMIT = {
  RELOAD_SAVED: 'RELOAD_SAVED',
  RELOAD_DETAIL_PROPERTY: 'RELOAD_DETAIL_PROPERTY',
  RELOAD_MY_PROPERTIES: 'RELOAD_MY_PROPERTIES'
};
